sudo: false
language: scala
scala:
- 2.10.5
- 2.11.6
jdk:
- oraclejdk7
script:
- sbt -Dfile.encoding=UTF8 -no-colors ++$TRAVIS_SCALA_VERSION test
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
notifications:
  hipchat:
    rooms:
      secure: GXAhV8e62YV98YT3ADu2SRqsrky5FSSt4sbBtnrddFpG3sul8kzbvY3kZz0lJh7FfmX3YlCHuA6AYfhOjE8bwLLojbmwvWUki+kWqotgUkTnevnX+Ugn9sOv3f3PQGXhffrSYtugYnImaJJk0AAhgPlg27UqQbbr9qCMph9Aj/Q=
